import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/custom/theme.provider";
import { SiteNavbar } from "@/components/custom/site/navbar";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import { ProgressiveBlur } from "@/components/ui/progressive-blur";
import SiteFooter from "@/components/custom/site/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F7F5F3]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          forcedTheme="light"
          disableTransitionOnChange
        >
          <div className="relative flex flex-col min-h-screen max-w-4xl mx-auto items-center justify-start">
            {/* Left vertical line */}
            <div className="w-px h-full absolute left-0 top-0 bg-[rgba(55,50,47,0.12)] shadow-[1px_0px_0px_white] z-0"></div>

            {/* Right vertical line */}
            <div className="w-px h-full absolute right-0 top-0 bg-[rgba(55,50,47,0.12)] shadow-[1px_0px_0px_white] z-0"></div>
            <SiteNavbar />
            {children}
            <SmoothCursor />
            <SiteFooter />
            <ProgressiveBlur height="5%" position="bottom" />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
